### ISSUE TITLE
Add content to GOV.UK search

### ISSUE THREAD

**Issue by jabley** [alphagov/design-principles#152]
As a [Kid Who Can't Write Good And Wanna Learn To Do Other Stuff Good Too](http://www.imdb.com/title/tt0196229/quotes?item=qt0375868)(sic),
I would like the style guide / design principles content to show up in search results,
So that I can Learn To Write Good.

**Comment by h-lame** [comment]
Closing because we're retiring this app and are about to archive the repo.  Now that the content for the design principles lives in other publishing apps across gov.uk it is part of search so I think we actually solved this in passing.
