### ISSUE TITLE
Reinstate "...not government needs"

### ISSUE THREAD

**Issue by blangry** [alphagov/design-principles#277]
Starting an issue to bring together some strands of discussion from twitter (https://twitter.com/joelanman/status/802134889160122368) around phrasing on the first principle.

It's about this commit here that rephrases "start with needs* user needs not government needs" as "start with user needs".
https://github.com/alphagov/design-principles/commit/bc650e3210754278c71b16c72ad2de2cbad353fb

I understand the thrust of this - it's certainly good to be clear about what we're talking about.
However, I feel like there are a couple of issues here - the first is that the term "user needs" is only adequately defined to people with a background in 'digital' (however we define that).

Both in my experience in departments, agencies and wider gov and anecdotally from others in a similar position, "user needs" can be interpreted quite widely and inserting the phrase "not government needs" is a good conversation starter with people new to digital development to make them consider who or what a user is.

I'm also aware of the "civil servants are users too" argument and heartily agree with it, but personally I'd probably draw a distinction between government needs and civil servant needs and definitely for projects in a department, I'd urge them to think of the users of a service first before the internal users.

I'd also back Caroline's suggestion of "Start with user needs* user needs not government needs", but definitely worth discussing.

I'm opening this issue here so that we can bring discussion somewhere a bit more longform than twitter and so that we can discuss from a cross-gov perspective.

**Comment by h-lame** [comment]
Closing because we're retiring this app and are about to archive the repo.  The content for the design principles now lives in other publishing apps across gov.uk so this is no longer a good place to track this issue.
